# Generated by Django 3.2 on 2022-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('github', 'Github')], max_length=20, null=True),
        ),
    ]
