# Generated by Django 3.2 on 2022-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('facebook', 'Facebook'), ('github', 'Github')], max_length=20, null=True),
        ),
    ]
