# Generated by Django 4.2.4 on 2023-08-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_variation_colour"),
        ("carts", "0002_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variations",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.variation",
            ),
        ),
    ]
