# Generated by Django 4.2.4 on 2023-08-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_variation_colour"),
        ("carts", "0003_remove_cartitem_variations_cartitem_variations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="quantity",
            new_name="total_quantity",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variations",
        ),
        migrations.CreateModel(
            name="CartItemVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "cart_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_item_variations",
                        to="carts.cartitem",
                    ),
                ),
                (
                    "variations",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.variation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
