# Generated by Django 4.2.4 on 2023-08-07 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_rename_total_quantity_cartitemvariation_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitemvariation",
            old_name="variations",
            new_name="variation",
        ),
    ]
