# Generated by Django 4.2.4 on 2023-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0006_rename_variations_cartitemvariation_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                default="sw6fxxuo4x2petpcgsydkt5lcm2opvf9", max_length=200
            ),
            preserve_default=False,
        ),
    ]
