# Generated by Django 4.2.4 on 2023-10-12 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0008_alter_cart_cart_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="total_quantity",
        ),
    ]
