# Generated by Django 4.1.7 on 2023-04-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Brand Name"),
        ),
    ]
