# Generated by Django 4.1.7 on 2023-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_brand_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Product Price"
            ),
        ),
    ]
