# Generated by Django 4.2.4 on 2023-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="variation_category",
        ),
        migrations.RemoveField(
            model_name="variation",
            name="variation_value",
        ),
        migrations.AddField(
            model_name="variation",
            name="colour",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="size",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
