# Generated by Django 4.2.4 on 2023-08-07 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_variation_variation_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="colour",
        ),
    ]
